name: Status Blog
markdown: redcarpet
pygments: true

# my custom rules

source:      /path/to/source
destination: /path/to/deploy

permalink: pretty
paginate: 10

# Uncomment the following, if you use a dedicated domain for Jekyll
baseurl: /updates
